import './globals.css';

import { Inter as FontSans } from 'next/font/google';

import { cn } from '@/lib/utils';
import ClientProviders from '@/features/shared/components/ClintProviders';
import Toast from '@/features/ui/components/Toast';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create-next-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body
        className={cn(
          'bg-background min-h-screen font-sans antialiased',
          fontSans.variable,
        )}
      >
        <ClientProviders>
          {children}
          <Toast></Toast>
        </ClientProviders>
      </body>
    </html>
  );
}
